var loadButton=document.getElementById("load-button")
var reloadButton=document.getElementById("reload-button")
var convertButton=document.getElementById("convert-button")
var saveButton=document.getElementById("save-button")
var resetButton=document.getElementById("reset-button")

loadButton.addEventListener("click", () => browser.runtime.sendMessage({action: "loadPage"}))
reloadButton.addEventListener("click", () => browser.runtime.sendMessage({action: "reloadPages"}))
convertButton.addEventListener("click", () => browser.runtime.sendMessage({action: "addPage"}))
saveButton.addEventListener("click", () => browser.runtime.sendMessage({action: "savePage"}))
resetButton.addEventListener("click", () => browser.runtime.sendMessage({action: "resetStorage"}))